/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminServerInfoRouteImport } from './routes/api/admin/server-info'
import { Route as ApiAdminPricingRouteImport } from './routes/api/admin/pricing'
import { Route as ApiAdminFeaturesRouteImport } from './routes/api/admin/features'
import { Route as ApiAdminAuthRouteImport } from './routes/api/admin/auth'
import { Route as ApiAdminAnnouncementsRouteImport } from './routes/api/admin/announcements'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminServerInfoRoute = ApiAdminServerInfoRouteImport.update({
  id: '/api/admin/server-info',
  path: '/api/admin/server-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingRoute = ApiAdminPricingRouteImport.update({
  id: '/api/admin/pricing',
  path: '/api/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeaturesRoute = ApiAdminFeaturesRouteImport.update({
  id: '/api/admin/features',
  path: '/api/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin/auth',
  path: '/api/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnnouncementsRoute = ApiAdminAnnouncementsRouteImport.update({
  id: '/api/admin/announcements',
  path: '/api/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/api/content': typeof ApiContentRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/server-info': typeof ApiAdminServerInfoRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/api/content': typeof ApiContentRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/server-info': typeof ApiAdminServerInfoRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/api/content': typeof ApiContentRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/server-info': typeof ApiAdminServerInfoRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/api/content'
    | '/api/admin/announcements'
    | '/api/admin/auth'
    | '/api/admin/features'
    | '/api/admin/pricing'
    | '/api/admin/server-info'
    | '/api/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/api/content'
    | '/api/admin/announcements'
    | '/api/admin/auth'
    | '/api/admin/features'
    | '/api/admin/pricing'
    | '/api/admin/server-info'
    | '/api/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/api/content'
    | '/api/admin/announcements'
    | '/api/admin/auth'
    | '/api/admin/features'
    | '/api/admin/pricing'
    | '/api/admin/server-info'
    | '/api/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiAdminAnnouncementsRoute: typeof ApiAdminAnnouncementsRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiAdminFeaturesRoute: typeof ApiAdminFeaturesRoute
  ApiAdminPricingRoute: typeof ApiAdminPricingRoute
  ApiAdminServerInfoRoute: typeof ApiAdminServerInfoRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/server-info': {
      id: '/api/admin/server-info'
      path: '/api/admin/server-info'
      fullPath: '/api/admin/server-info'
      preLoaderRoute: typeof ApiAdminServerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing': {
      id: '/api/admin/pricing'
      path: '/api/admin/pricing'
      fullPath: '/api/admin/pricing'
      preLoaderRoute: typeof ApiAdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/features': {
      id: '/api/admin/features'
      path: '/api/admin/features'
      fullPath: '/api/admin/features'
      preLoaderRoute: typeof ApiAdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth': {
      id: '/api/admin/auth'
      path: '/api/admin/auth'
      fullPath: '/api/admin/auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/announcements': {
      id: '/api/admin/announcements'
      path: '/api/admin/announcements'
      fullPath: '/api/admin/announcements'
      preLoaderRoute: typeof ApiAdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  ApiContentRoute: ApiContentRoute,
  ApiAdminAnnouncementsRoute: ApiAdminAnnouncementsRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiAdminFeaturesRoute: ApiAdminFeaturesRoute,
  ApiAdminPricingRoute: ApiAdminPricingRoute,
  ApiAdminServerInfoRoute: ApiAdminServerInfoRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
